.PHONY: help

test:
	go test -v -run='^\QTest_Check_' ./
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "This Makefile is to test whether the program can simulate normal distribution normally."
	@echo ""
	@echo "Available targets:"
	@echo "  test     - unit test"
	@echo ""